[workspace]
members = [
    "crates/physics-dsp",
    "crates/physics-piano",
    "crates/physics-guitar",
    "crates/physics-presets",
    "xtask"
]
resolver = "3"

[workspace.package]
version = "0.3.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
split-debuginfo = "unpacked"
debug = 1
